/**
 * medicineSafetyService.ts — ZenithRx Master Medicine Catalogue & Deep Clinical Data Model (§7, §8, §34)
 * Models medicines around Product + Formulation + Packaging hierarchy per Uganda NDA and WHO INN standards.
 */

import {
  MasterMedicineItem,
  DrugInteraction,
  PrescriptionLegalStatus,
  ControlledScheduleType,
  StorageTemperatureClass,
  MedicineLifecycleStatus,
  PregnancyCategory,
} from '../types';

export type {
  MasterMedicineItem,
  DrugInteraction,
  PrescriptionLegalStatus,
  ControlledScheduleType,
  StorageTemperatureClass,
  MedicineLifecycleStatus,
  PregnancyCategory,
};

const STORAGE_KEY_MASTER_CATALOGUE = 'zenithrx_master_medicines_v2';

export const INITIAL_MASTER_MEDICINES: MasterMedicineItem[] = [
  // ─── 1. PARACETAMOL PRODUCT GROUP ──────────────────────────────────────────
  {
    id: 'med-para-tab-500',
    productGroupId: 'PROD-PARACETAMOL',
    genericInnName: 'Paracetamol (Acetaminophen)',
    genericName: 'Paracetamol',
    brandName: 'Panadol Extra 500mg',
    activeIngredients: ['Paracetamol 500mg', 'Caffeine 65mg'],
    ndaRegistrationNumber: 'NDA/MAL/0411/2020',
    category: 'Analgesics & Antipyretics',
    therapeuticClass: 'Aniline Derivative Analgesic / CNS Stimulant',
    atcClassificationCode: 'N02BE51',
    form: 'Film-Coated Tablet',
    dosageForm: 'Film-Coated Tablet',
    strength: '500mg / 65mg',
    route: 'Oral',
    packageSize: 'Box of 100 Tablets (10x10 Blister Pack)',
    packageType: 'Blister Pack in Outer Carton',
    standardUnit: 'tablets',
    unitOfMeasure: 'tablets',
    packQuantity: 100,
    manufacturer: 'GlaxoSmithKline (GSK)',
    countryOfManufacture: 'Kenya',
    prescriptionStatus: 'OTC',
    controlledStatus: 'Non-Controlled',
    isPoisonScheduleA: false,
    minStockLevel: 200,
    maxStockLevel: 5000,
    reorderLevel: 500,
    reorderQuantity: 1000,
    isColdChainRequired: false,
    storageTemperatureRange: '15°C - 30°C',
    temperatureRequirement: 'Controlled Room (15°C - 30°C)',
    storageRequirements: 'Store below 30°C in a dry place. Protect from moisture and direct heat.',
    isLightSensitive: false,
    specialHandlingRequirements: 'Keep out of reach of children.',
    standardDoseAdult: '1 to 2 tablets (500mg - 1000mg) every 4-6 hours as needed. Max 4000mg/24h.',
    standardDosePediatric: 'Not recommended for children under 12 years (use oral suspension).',
    maxDailyDose: '4000mg paracetamol / 24 hours',
    maxDailyDoseNumericMg: 4000,
    pregnancyCategory: 'B',
    pregnancyWarning: 'Considered safe for short-term use in all trimesters at lowest therapeutic dose.',
    ageRestrictions: 'Adults and adolescents aged 12 years and above only.',
    commonAllergies: ['Paracetamol hypersensitivity', 'Severe hepatic impairment'],
    contraindications: ['Severe active liver disease / cirrhosis', 'Known G6PD deficiency (high doses)'],
    counselingNotes: 'Do not take concurrently with other paracetamol-containing cough, cold or flu remedies.',
    averageWholesalePriceUgx: 200,
    suggestedRetailPriceUgx: 350,
    verifiedByNda: true,
    isActive: true,
    status: 'active',
  },
  {
    id: 'med-para-susp-120',
    productGroupId: 'PROD-PARACETAMOL',
    genericInnName: 'Paracetamol (Acetaminophen)',
    genericName: 'Paracetamol',
    brandName: 'Calpol Infant Suspension 120mg/5ml',
    activeIngredients: ['Paracetamol 120mg/5mL'],
    ndaRegistrationNumber: 'NDA/MAL/0198/2019',
    category: 'Analgesics & Antipyretics',
    therapeuticClass: 'Aniline Derivative Pediatric Analgesic',
    atcClassificationCode: 'N02BE01',
    form: 'Oral Suspension',
    dosageForm: 'Oral Suspension (Strawberry Flavor)',
    strength: '120mg / 5mL',
    route: 'Oral',
    packageSize: '100 mL Amber Glass Bottle with 5mL Double-Ended Syringe',
    packageType: 'Amber Glass Bottle with Child-Resistant Cap',
    standardUnit: 'mL',
    unitOfMeasure: 'mL',
    packQuantity: 100,
    manufacturer: 'GlaxoSmithKline (GSK)',
    countryOfManufacture: 'UK',
    prescriptionStatus: 'OTC',
    controlledStatus: 'Non-Controlled',
    isPoisonScheduleA: false,
    minStockLevel: 20,
    maxStockLevel: 200,
    reorderLevel: 40,
    reorderQuantity: 60,
    isColdChainRequired: false,
    storageTemperatureRange: '15°C - 25°C',
    temperatureRequirement: 'Room Temp (15°C - 25°C)',
    storageRequirements: 'Store below 25°C. Do not freeze. Discard remaining suspension 30 days after opening.',
    isLightSensitive: true,
    specialHandlingRequirements: 'Shake bottle vigorously for at least 10 seconds before every administration.',
    standardDoseAdult: 'Use tablet formulation for adults.',
    standardDosePediatric: '10-15 mg/kg/dose every 4-6 hours (e.g., 3-6 months: 2.5ml; 2-4 years: 7.5ml).',
    maxDailyDose: '60mg/kg/day in 4 divided doses',
    maxDailyDoseNumericMg: 2400,
    pregnancyCategory: 'B',
    ageRestrictions: 'Infants from 2 months (post-vaccination fever) up to 6 years.',
    commonAllergies: ['Paracetamol hypersensitivity'],
    contraindications: ['Severe liver failure'],
    counselingNotes: 'Always use the supplied measuring syringe; never use a household teaspoon.',
    averageWholesalePriceUgx: 8500,
    suggestedRetailPriceUgx: 12000,
    verifiedByNda: true,
    isActive: true,
    status: 'active',
  },

  // ─── 2. CO-AMOXICLAV PRODUCT GROUP ─────────────────────────────────────────
  {
    id: 'med-amox-tab-625',
    productGroupId: 'PROD-CO-AMOXICLAV',
    genericInnName: 'Amoxicillin + Clavulanic Acid',
    genericName: 'Co-Amoxiclav',
    brandName: 'Augmentin 625mg',
    activeIngredients: ['Amoxicillin 500mg (as Trihydrate)', 'Clavulanic Acid 125mg (as Potassium Clavulanate)'],
    ndaRegistrationNumber: 'NDA/MAL/0891/2021',
    category: 'Antibiotics',
    therapeuticClass: 'Beta-lactamase inhibitor combination',
    atcClassificationCode: 'J01CR02',
    form: 'Film-Coated Tablet',
    dosageForm: 'Oval Film-Coated Tablet',
    strength: '625mg (500mg/125mg)',
    route: 'Oral',
    packageSize: 'Box of 14 Tablets (2x7 Foil Blister)',
    packageType: 'Desiccant-Lined Aluminum Foil Blister',
    standardUnit: 'tablets',
    unitOfMeasure: 'tablets',
    packQuantity: 14,
    manufacturer: 'SmithKline Beecham / GSK',
    countryOfManufacture: 'UK',
    prescriptionStatus: 'POM',
    controlledStatus: 'Non-Controlled',
    isPoisonScheduleA: false,
    minStockLevel: 50,
    maxStockLevel: 800,
    reorderLevel: 100,
    reorderQuantity: 200,
    isColdChainRequired: false,
    storageTemperatureRange: '15°C - 25°C',
    temperatureRequirement: 'Room Temp (15°C - 25°C)',
    storageRequirements: 'Store in original packaging below 25°C. Clavulanate is highly hygroscopic; do not puncture blisters until ready to swallow.',
    isLightSensitive: true,
    specialHandlingRequirements: 'Moisture sensitive. Do not repackage into loose tablet envelopes.',
    standardDoseAdult: '1 tablet (625mg) every 12 hours (BD) or 1 tablet every 8 hours (TDS) for severe infections.',
    standardDosePediatric: 'Use oral suspension formulation for children weighing < 40 kg.',
    maxDailyDose: '3000mg amoxicillin equivalent / day',
    maxDailyDoseNumericMg: 3000,
    pregnancyCategory: 'B',
    pregnancyWarning: 'Generally safe in 2nd/3rd trimester. Caution with preterm PROM (risk of necrotizing enterocolitis).',
    ageRestrictions: 'Adults and children weighing 40 kg and above.',
    commonAllergies: ['Penicillin', 'Beta-lactam antibiotics', 'Cephalosporins (cross-allergy 5-10%)'],
    contraindications: ['History of penicillin-associated cholestatic jaundice / liver dysfunction'],
    counselingNotes: 'Take immediately at the start of a meal to enhance absorption and prevent stomach upset. Complete full course.',
    averageWholesalePriceUgx: 2200,
    suggestedRetailPriceUgx: 3000,
    verifiedByNda: true,
    isActive: true,
    status: 'active',
  },
  {
    id: 'med-amox-susp-228',
    productGroupId: 'PROD-CO-AMOXICLAV',
    genericInnName: 'Amoxicillin + Clavulanic Acid',
    genericName: 'Co-Amoxiclav',
    brandName: 'Augmentin ES-600 Powder for Oral Suspension',
    activeIngredients: ['Amoxicillin 200mg/5mL', 'Clavulanic Acid 28.5mg/5mL'],
    ndaRegistrationNumber: 'NDA/MAL/0892/2021',
    category: 'Antibiotics',
    therapeuticClass: 'Pediatric Beta-lactamase inhibitor combination',
    atcClassificationCode: 'J01CR02',
    form: 'Oral Suspension',
    dosageForm: 'Dry Powder for Reconstitution (Oral Suspension)',
    strength: '228.5mg / 5mL',
    route: 'Oral',
    packageSize: '70 mL HDPE Bottle with Reconstitution Mark & Measuring Cup',
    packageType: 'HDPE Bottle with Silica Cap',
    standardUnit: 'mL',
    unitOfMeasure: 'mL',
    packQuantity: 70,
    manufacturer: 'SmithKline Beecham / GSK',
    countryOfManufacture: 'UK',
    prescriptionStatus: 'POM',
    controlledStatus: 'Non-Controlled',
    isPoisonScheduleA: false,
    minStockLevel: 15,
    maxStockLevel: 150,
    reorderLevel: 30,
    reorderQuantity: 50,
    isColdChainRequired: true,
    storageTemperatureRange: '2°C - 8°C (After reconstitution)',
    temperatureRequirement: 'Cold Chain (2°C - 8°C)',
    storageRequirements: 'Store dry powder below 25°C. Once reconstituted with boiled cooled water, MUST be refrigerated at 2°C - 8°C and discarded after 7 days.',
    isLightSensitive: true,
    specialHandlingRequirements: 'Reconstitute strictly with purified boiled and cooled water up to the bottle line. Keep refrigerated.',
    standardDoseAdult: 'Use tablet formulation for adults.',
    standardDosePediatric: '25/3.6 to 45/6.4 mg/kg/day divided into 2 doses every 12 hours.',
    maxDailyDose: '90/6.4 mg/kg/day in recurrent acute otitis media',
    maxDailyDoseNumericMg: 1500,
    pregnancyCategory: 'B',
    ageRestrictions: 'Pediatric patients aged 2 months to 12 years.',
    commonAllergies: ['Penicillin allergy'],
    contraindications: ['Penicillin-induced hepatic impairment'],
    counselingNotes: 'Keep in refrigerator door. Shake well before every dose. Throw away unused bottle after 7 days.',
    averageWholesalePriceUgx: 18000,
    suggestedRetailPriceUgx: 26000,
    verifiedByNda: true,
    isActive: true,
    status: 'active',
  },

  // ─── 3. AMLODIPINE PRODUCT GROUP ───────────────────────────────────────────
  {
    id: 'med-amlo-tab-5',
    productGroupId: 'PROD-AMLODIPINE',
    genericInnName: 'Amlodipine Besylate',
    genericName: 'Amlodipine',
    brandName: 'Norvasc 5mg',
    activeIngredients: ['Amlodipine Besylate 5mg equivalent'],
    ndaRegistrationNumber: 'NDA/MAL/1102/2020',
    category: 'Cardiovascular',
    therapeuticClass: 'Dihydropyridine Calcium Channel Blocker',
    atcClassificationCode: 'C08CA01',
    form: 'Tablet',
    dosageForm: 'Octagonal White Tablet',
    strength: '5mg',
    route: 'Oral',
    packageSize: 'Box of 30 Tablets (3x10 Blister Pack)',
    packageType: 'PVC/PVDC/Aluminum Blister',
    standardUnit: 'tablets',
    unitOfMeasure: 'tablets',
    packQuantity: 30,
    manufacturer: 'Pfizer Inc.',
    countryOfManufacture: 'Germany',
    prescriptionStatus: 'POM',
    controlledStatus: 'Non-Controlled',
    isPoisonScheduleA: false,
    minStockLevel: 60,
    maxStockLevel: 1200,
    reorderLevel: 150,
    reorderQuantity: 300,
    isColdChainRequired: false,
    storageTemperatureRange: '15°C - 30°C',
    temperatureRequirement: 'Controlled Room (15°C - 30°C)',
    storageRequirements: 'Store below 30°C in original container.',
    isLightSensitive: false,
    specialHandlingRequirements: 'Standard pharmaceutical storage.',
    standardDoseAdult: '5mg once daily (OD), may titrate to 10mg once daily after 2-4 weeks.',
    standardDosePediatric: '2.5mg to 5mg once daily in children 6-17 years with hypertension.',
    maxDailyDose: '10mg / day',
    maxDailyDoseNumericMg: 10,
    pregnancyCategory: 'C',
    pregnancyWarning: 'Use only if potential benefit justifies potential fetal risk; CCBs can inhibit uterine contractions.',
    ageRestrictions: 'Children under 6 years not evaluated.',
    commonAllergies: ['Dihydropyridine hypersensitivity'],
    contraindications: ['Severe hypotension', 'Cardiogenic shock', 'Clinically significant aortic stenosis'],
    counselingNotes: 'Take once daily with or without food. May cause mild ankle swelling; report severe edema or dizziness.',
    averageWholesalePriceUgx: 1000,
    suggestedRetailPriceUgx: 1500,
    verifiedByNda: true,
    isActive: true,
    status: 'active',
  },
  {
    id: 'med-amlo-tab-10',
    productGroupId: 'PROD-AMLODIPINE',
    genericInnName: 'Amlodipine Besylate',
    genericName: 'Amlodipine',
    brandName: 'Norvasc 10mg',
    activeIngredients: ['Amlodipine Besylate 10mg equivalent'],
    ndaRegistrationNumber: 'NDA/MAL/1103/2020',
    category: 'Cardiovascular',
    therapeuticClass: 'Dihydropyridine Calcium Channel Blocker',
    atcClassificationCode: 'C08CA01',
    form: 'Tablet',
    dosageForm: 'Octagonal White Tablet (Cross-Scored)',
    strength: '10mg',
    route: 'Oral',
    packageSize: 'Box of 30 Tablets (3x10 Blister Pack)',
    packageType: 'PVC/PVDC/Aluminum Blister',
    standardUnit: 'tablets',
    unitOfMeasure: 'tablets',
    packQuantity: 30,
    manufacturer: 'Pfizer Inc.',
    countryOfManufacture: 'Germany',
    prescriptionStatus: 'POM',
    controlledStatus: 'Non-Controlled',
    isPoisonScheduleA: false,
    minStockLevel: 60,
    maxStockLevel: 1200,
    reorderLevel: 150,
    reorderQuantity: 300,
    isColdChainRequired: false,
    storageTemperatureRange: '15°C - 30°C',
    temperatureRequirement: 'Controlled Room (15°C - 30°C)',
    storageRequirements: 'Store below 30°C in original container.',
    isLightSensitive: false,
    specialHandlingRequirements: 'Standard pharmaceutical storage.',
    standardDoseAdult: '10mg once daily in the morning.',
    maxDailyDose: '10mg / day',
    maxDailyDoseNumericMg: 10,
    pregnancyCategory: 'C',
    commonAllergies: ['Dihydropyridine hypersensitivity'],
    contraindications: ['Severe hypotension', 'Cardiogenic shock'],
    counselingNotes: 'Take consistently at the same time each morning. Monitor blood pressure weekly.',
    averageWholesalePriceUgx: 1500,
    suggestedRetailPriceUgx: 2200,
    verifiedByNda: true,
    isActive: true,
    status: 'active',
  },

  // ─── 4. INSULIN GLARGINE (COLD CHAIN) ──────────────────────────────────────
  {
    id: 'med-ins-glarg-100',
    productGroupId: 'PROD-INSULIN-GLARGINE',
    genericInnName: 'Insulin Glargine (Recombinant DNA)',
    genericName: 'Insulin Glargine',
    brandName: 'Lantus SoloStar 100 IU/mL',
    activeIngredients: ['Insulin Glargine 100 Units/mL (3.64mg)'],
    ndaRegistrationNumber: 'NDA/BIO/0081/2022',
    category: 'Diabetes',
    therapeuticClass: 'Long-Acting Basal Insulin Analog',
    atcClassificationCode: 'A10AE04',
    form: 'Injection',
    dosageForm: 'Prefilled Disposable Insulin Pen',
    strength: '100 IU/mL (3 mL per pen)',
    route: 'Subcutaneous',
    packageSize: 'Box of 5 SoloStar Prefilled Pens (3 mL each, Total 1500 IU)',
    packageType: 'Insulin Cartridge in Mechanical Disposable Pen',
    standardUnit: 'vial',
    unitOfMeasure: 'pens',
    packQuantity: 5,
    manufacturer: 'Sanofi-Aventis Deutschland GmbH',
    countryOfManufacture: 'Germany',
    prescriptionStatus: 'POM',
    controlledStatus: 'Non-Controlled',
    isPoisonScheduleA: true,
    minStockLevel: 5,
    maxStockLevel: 50,
    reorderLevel: 10,
    reorderQuantity: 20,
    isColdChainRequired: true,
    storageTemperatureRange: '2°C - 8°C (Do NOT Freeze)',
    temperatureRequirement: 'Cold Chain (2°C - 8°C)',
    storageRequirements: 'Store unopened pens in refrigerator at 2°C - 8°C. Do NOT freeze. Protect from light. In-use pen can be kept at room temp (< 30°C) for up to 28 days.',
    isLightSensitive: true,
    specialHandlingRequirements: 'Cold chain validated transport required with ice packs and temperature logger.',
    standardDoseAdult: 'Individualized once daily subcutaneous injection at the same time each day (typically bedtime).',
    standardDosePediatric: 'Initiate based on glycemic targets and endocrinologist titration in type 1 diabetes.',
    maxDailyDose: 'Titrated according to blood glucose logs',
    pregnancyCategory: 'C',
    blackboxWarning: 'Hypoglycemia is the most common adverse reaction. Do not dilute or mix with other insulins.',
    commonAllergies: ['Insulin glargine excipient allergy (zinc, m-cresol)'],
    contraindications: ['Hypoglycemic episodes'],
    counselingNotes: 'Never inject into a vein or muscle. Rotate injection sites across abdomen, thigh, or upper arm.',
    averageWholesalePriceUgx: 45000,
    suggestedRetailPriceUgx: 60000,
    verifiedByNda: true,
    isActive: true,
    status: 'active',
  },

  // ─── 5. MORPHINE SULPHATE (CLASS A NARCOTIC / DDA LOCKABLE SAFE) ───────────
  {
    id: 'med-morph-oral-10',
    productGroupId: 'PROD-MORPHINE',
    genericInnName: 'Morphine Sulphate',
    genericName: 'Morphine',
    brandName: 'Sevredol 10mg/5ml Oral Liquid',
    activeIngredients: ['Morphine Sulphate 10mg / 5mL'],
    ndaRegistrationNumber: 'NDA/DD/0014/2021',
    category: 'Controlled Narcotics',
    therapeuticClass: 'Opioid Analgesic (Phenanthrene Derivative)',
    atcClassificationCode: 'N02AA01',
    form: 'Oral Suspension',
    dosageForm: 'Clear Aqueous Oral Solution',
    strength: '10mg / 5mL',
    route: 'Oral',
    packageSize: '100 mL Amber Glass Bottle with Child-Resistant Tamper-Evident Cap',
    packageType: 'Amber Glass Bottle with DDA Seal',
    standardUnit: 'mL',
    unitOfMeasure: 'mL',
    packQuantity: 100,
    manufacturer: 'Napp Pharmaceuticals / Mundipharma',
    countryOfManufacture: 'UK',
    prescriptionStatus: 'POM',
    controlledStatus: 'Class A Narcotic (Lockable Safe)',
    isPoisonScheduleA: true,
    minStockLevel: 2,
    maxStockLevel: 15,
    reorderLevel: 4,
    reorderQuantity: 6,
    isColdChainRequired: false,
    storageTemperatureRange: '15°C - 25°C',
    temperatureRequirement: 'Room Temp (15°C - 25°C)',
    storageRequirements: 'Store in Uganda Dangerous Drugs Act (DDA) locked poison safe. Protect from light.',
    isLightSensitive: true,
    specialHandlingRequirements: 'Requires dual pharmacist signature, patient national ID verification, and entry into NDA Dangerous Drugs Register.',
    standardDoseAdult: '5mg - 20mg every 4 hours as needed for severe breakthrough pain in palliative/malignant care.',
    maxDailyDose: 'Individually titrated without ceiling in palliative oncology under clinical supervision',
    pregnancyCategory: 'C',
    pregnancyWarning: 'Chronic maternal use causes neonatal opioid withdrawal syndrome (NOWS).',
    blackboxWarning: 'High addiction, abuse, and misuse potential. Severe respiratory depression risk when co-administered with benzodiazepines or alcohol.',
    commonAllergies: ['Opioid hypersensitivity'],
    contraindications: ['Acute respiratory depression', 'Severe bronchial asthma', 'Paralytic ileus', 'Head injury with raised ICP'],
    counselingNotes: 'May cause drowsiness, constipation, and dizziness. Co-prescribe stool softener (e.g. Bisacodyl). Do not drive or operate machinery.',
    averageWholesalePriceUgx: 38000,
    suggestedRetailPriceUgx: 52000,
    verifiedByNda: true,
    isActive: true,
    status: 'active',
  },

  // ─── 6. SALBUTAMOL PRODUCT GROUP ───────────────────────────────────────────
  {
    id: 'med-salb-inh-100',
    productGroupId: 'PROD-SALBUTAMOL',
    genericInnName: 'Salbutamol Sulfate',
    genericName: 'Salbutamol',
    brandName: 'Ventolin Evohaler 100mcg',
    activeIngredients: ['Salbutamol Sulfate 100mcg per metered actuation'],
    ndaRegistrationNumber: 'NDA/MAL/0192/2018',
    category: 'Respiratory',
    therapeuticClass: 'Short-Acting Beta-2 Adrenergic Agonist (SABA)',
    atcClassificationCode: 'R03AC02',
    form: 'Inhaler',
    dosageForm: 'Pressurized Metered Dose Inhaler (pMDI)',
    strength: '100mcg / puff (200 actuations)',
    route: 'Inhalation',
    packageSize: '1 Inhaler Canister in Plastic Actuator with Blue Dust Cap (200 Doses)',
    packageType: 'Pressurized Aluminum Canister with Fluorocarbon Propellant',
    standardUnit: 'inhaler',
    unitOfMeasure: 'doses',
    packQuantity: 200,
    manufacturer: 'Glaxo Wellcome / GSK',
    countryOfManufacture: 'UK',
    prescriptionStatus: 'POM',
    controlledStatus: 'Non-Controlled',
    isPoisonScheduleA: false,
    minStockLevel: 25,
    maxStockLevel: 300,
    reorderLevel: 50,
    reorderQuantity: 100,
    isColdChainRequired: false,
    storageTemperatureRange: '15°C - 30°C',
    temperatureRequirement: 'Controlled Room (15°C - 30°C)',
    storageRequirements: 'Store below 30°C. Protect from frost and direct sunlight. Pressurized canister; do not puncture or burn even when empty.',
    isLightSensitive: false,
    specialHandlingRequirements: 'Pressurized canister.',
    standardDoseAdult: '1 to 2 inhalations (100-200mcg) every 4-6 hours for acute relief of bronchospasm.',
    standardDosePediatric: '1 inhalation (100mcg) via spacer device, increase to 2 puffs if required.',
    maxDailyDose: '8 puffs (800mcg) per 24 hours without clinical reassessment',
    maxDailyDoseNumericMg: 0.8,
    pregnancyCategory: 'C',
    commonAllergies: ['Salbutamol hypersensitivity', 'Propellant allergy'],
    contraindications: ['Hypersensitivity to salbutamol'],
    counselingNotes: 'Shake well before spraying. Breathe out fully, seal lips on mouthpiece, press down while breathing in deeply, and hold breath for 10 seconds.',
    averageWholesalePriceUgx: 18000,
    suggestedRetailPriceUgx: 25000,
    verifiedByNda: true,
    isActive: true,
    status: 'active',
  },

  // ─── 7. ARTEMETHER + LUMEFANTRINE (ANTIMALARIAL) ───────────────────────────
  {
    id: 'med-artem-tab-20-120',
    productGroupId: 'PROD-ARTEMETHER-LUMEFANTRINE',
    genericInnName: 'Artemether + Lumefantrine',
    genericName: 'Artemether / Lumefantrine',
    brandName: 'Coartem 20/120mg Dispersible',
    activeIngredients: ['Artemether 20mg', 'Lumefantrine 120mg'],
    ndaRegistrationNumber: 'NDA/MAL/0710/2019',
    category: 'Antimalarials',
    therapeuticClass: 'Artemisinin-based Combination Therapy (ACT)',
    atcClassificationCode: 'P01BF01',
    form: 'Tablet',
    dosageForm: 'Sweetened Dispersible Tablet',
    strength: '20mg / 120mg',
    route: 'Oral',
    packageSize: 'Box of 24 Dispersible Tablets (4x6 Blister Pack for 25-35kg)',
    packageType: 'Aluminum/Aluminum Cold-Form Blister',
    standardUnit: 'tablets',
    unitOfMeasure: 'tablets',
    packQuantity: 24,
    manufacturer: 'Novartis Pharma AG / Cipla Quality Chemicals Uganda',
    countryOfManufacture: 'Uganda',
    prescriptionStatus: 'POM',
    controlledStatus: 'Non-Controlled',
    isPoisonScheduleA: false,
    minStockLevel: 100,
    maxStockLevel: 2500,
    reorderLevel: 250,
    reorderQuantity: 500,
    isColdChainRequired: false,
    storageTemperatureRange: '15°C - 30°C',
    temperatureRequirement: 'Controlled Room (15°C - 30°C)',
    storageRequirements: 'Store in original package below 30°C. Protect from moisture.',
    isLightSensitive: true,
    specialHandlingRequirements: 'Uganda Ministry of Health 1st-Line Uncomplicated Malaria Therapy.',
    standardDoseAdult: '4 tablets initially, then 4 tablets after 8 hours, followed by 4 tablets twice daily (morning and evening) for the next 2 days (Total 24 tablets).',
    standardDosePediatric: 'Weight-based 6-dose regimen: 5-14kg (1 tab BD x 3d), 15-24kg (2 tabs BD x 3d), 25-34kg (3 tabs BD x 3d).',
    maxDailyDose: '8 tablets / day in adults',
    pregnancyCategory: 'C',
    pregnancyWarning: 'Recommended in 2nd and 3rd trimester. For 1st trimester, oral quinine + clindamycin is primary guideline unless unavailable.',
    ageRestrictions: 'Infants weighing ≥ 5 kg.',
    commonAllergies: ['Artemisinin derivative hypersensitivity'],
    contraindications: ['Severe complicated malaria (use IV artesunate)', 'Pre-existing QTc prolongation'],
    counselingNotes: 'MUST be taken with fatty food, whole milk, or porridge to ensure absorption of lumefantrine.',
    averageWholesalePriceUgx: 8000,
    suggestedRetailPriceUgx: 12000,
    verifiedByNda: true,
    isActive: true,
    status: 'active',
  },
];

export const MASTER_DRUG_INTERACTIONS: DrugInteraction[] = [
  {
    id: 'int-001',
    primaryDrugGeneric: 'Metformin',
    interactingDrugGeneric: 'Contrast Media (Iodinated)',
    severity: 'Severe',
    clinicalEffect: 'Iodinated contrast may cause acute renal failure leading to metformin accumulation and fatal lactic acidosis.',
    managementAdvice: 'Withhold Metformin at least 48 hours before and 48 hours after iodinated radiological contrast procedures.',
  },
  {
    id: 'int-002',
    primaryDrugGeneric: 'Amlodipine',
    interactingDrugGeneric: 'Simvastatin',
    severity: 'Moderate',
    clinicalEffect: 'Amlodipine inhibits CYP3A4, increasing simvastatin serum concentrations by up to 77% (rhabdomyolysis risk).',
    managementAdvice: 'Limit Simvastatin dose to a maximum of 20mg daily when co-administered with Amlodipine, or switch to Rosuvastatin.',
  },
  {
    id: 'int-003',
    primaryDrugGeneric: 'Artemether + Lumefantrine',
    interactingDrugGeneric: 'Ketoconazole / Erythromycin',
    severity: 'Severe',
    clinicalEffect: 'CYP3A4 inhibition elevates lumefantrine concentrations, risking additive cardiac QTc interval prolongation.',
    managementAdvice: 'Avoid concomitant administration with strong CYP3A4 inhibitors. Monitor ECG rhythm in high-risk patients.',
  },
  {
    id: 'int-004',
    primaryDrugGeneric: 'Morphine Sulphate',
    interactingDrugGeneric: 'Diazepam / Benzodiazepines',
    severity: 'Contraindicated',
    clinicalEffect: 'Profound additive central nervous system depression, respiratory arrest, coma, and death.',
    managementAdvice: 'Strictly avoid concomitant use unless no alternative exists. Keep Naloxone antidote readily available.',
  },
];

class MedicineSafetyService {
  private medicines: MasterMedicineItem[] = [];
  private interactions: DrugInteraction[] = [];

  constructor() {
    const cached = localStorage.getItem(STORAGE_KEY_MASTER_CATALOGUE);
    if (cached) {
      try {
        this.medicines = JSON.parse(cached);
      } catch {
        this.medicines = INITIAL_MASTER_MEDICINES;
      }
    } else {
      this.medicines = INITIAL_MASTER_MEDICINES;
      this.saveToStorage();
    }
    this.interactions = MASTER_DRUG_INTERACTIONS;
  }

  private saveToStorage() {
    try {
      localStorage.setItem(STORAGE_KEY_MASTER_CATALOGUE, JSON.stringify(this.medicines));
    } catch {
      // Ignore storage errors
    }
  }

  public getAll(): MasterMedicineItem[] {
    return [...this.medicines];
  }

  public getById(id: string): MasterMedicineItem | undefined {
    return this.medicines.find((m) => m.id === id);
  }

  public getProductGroups(): Record<string, MasterMedicineItem[]> {
    const groups: Record<string, MasterMedicineItem[]> = {};
    this.medicines.forEach((med) => {
      const key = med.productGroupId || med.genericInnName || med.genericName;
      if (!groups[key]) {
        groups[key] = [];
      }
      groups[key].push(med);
    });
    return groups;
  }

  public getInteractions(): DrugInteraction[] {
    return [...this.interactions];
  }

  public addMedicine(item: MasterMedicineItem): MasterMedicineItem {
    this.medicines.push(item);
    this.saveToStorage();
    return item;
  }

  public updateMedicine(id: string, updates: Partial<MasterMedicineItem>): MasterMedicineItem | null {
    const idx = this.medicines.findIndex((m) => m.id === id);
    if (idx === -1) return null;
    this.medicines[idx] = { ...this.medicines[idx], ...updates };
    this.saveToStorage();
    return this.medicines[idx];
  }
}

export const medicineSafetyService = new MedicineSafetyService();

export const getMasterMedicines = (): MasterMedicineItem[] => {
  return medicineSafetyService.getAll();
};
