-- ============================================================================
-- ZenithRx Patient Medication Profile & Clinical Interaction Engine (§11.14, §11.26)
-- Context-Aware Drug-to-Drug, Drug-to-Allergy, Drug-to-Disease & OTC Interaction Screening
-- Pharmacist Decision-Support System with Immutable Clinical Override Auditing
-- ============================================================================

-- 1. Enums for Clinical Safety Alerts
DO $$ BEGIN
    CREATE TYPE clinical_alert_severity AS ENUM (
        'contraindicated_fatal_risk', -- Absolute contraindication / life-threatening
        'major_clinical_hazard',       -- Significant risk; requires intervention/close monitoring
        'moderate_advisory',           -- Moderate interaction; dose adjustment or timing adjustment
        'minor_precaution'             -- Low clinical risk / informational
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE clinical_alert_category AS ENUM (
        'drug_drug_interaction',
        'allergy_cross_reactivity',
        'disease_contraindication',
        'previous_adr_recurrence',
        'duplicate_therapy',
        'otc_herb_drug_interaction'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE pharmacist_decision_action AS ENUM (
        'approved_safe',
        'overridden_with_justification',
        'prescriber_clarification_requested',
        'rejected_safety_grounds'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. Patient Medication Profile (Comprehensive Clinical Context)
CREATE TABLE IF NOT EXISTS public.patient_medication_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id VARCHAR(100) NOT NULL UNIQUE,
    tenant_id VARCHAR(100) NOT NULL,
    patient_name VARCHAR(255) NOT NULL,
    patient_nin_or_id VARCHAR(100),
    date_of_birth DATE,
    gender VARCHAR(20),
    phone VARCHAR(50),
    
    -- Clinical History Arrays (Structured JSONB)
    current_medications JSONB DEFAULT '[]'::jsonb,      -- Active prescribed therapies
    previous_medications JSONB DEFAULT '[]'::jsonb,     -- Past completed/discontinued therapies
    known_allergies JSONB DEFAULT '[]'::jsonb,          -- Drug & substance allergies with reaction severity
    previous_adrs JSONB DEFAULT '[]'::jsonb,            -- Formally recorded Adverse Drug Reactions
    chronic_conditions JSONB DEFAULT '[]'::jsonb,      -- Voluntarily reported chronic diseases (e.g. Asthma, CKD, Diabetes)
    otc_medications_reported JSONB DEFAULT '[]'::jsonb, -- Patient-reported OTC drugs, herbs, dietary supplements
    
    -- Metrics
    total_prescriptions_count INTEGER DEFAULT 0,
    total_dispensing_count INTEGER DEFAULT 0,
    last_clinical_review_date TIMESTAMPTZ,
    last_reviewed_by_pharmacist VARCHAR(255),
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Master Clinical Knowledge Base (Interactions, Allergy Cross-Reactivity, Disease Flags)
CREATE TABLE IF NOT EXISTS public.clinical_interaction_rules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    rule_type clinical_alert_category NOT NULL,
    primary_agent_generic VARCHAR(255) NOT NULL,
    trigger_condition_or_agent VARCHAR(255) NOT NULL, -- Interacting drug, allergy class, or chronic condition
    severity clinical_alert_severity NOT NULL,
    clinical_mechanism TEXT NOT NULL,
    clinical_hazard_summary TEXT NOT NULL,
    recommended_pharmacist_action TEXT NOT NULL,
    reference_source VARCHAR(100) DEFAULT 'British National Formulary (BNF) / Uganda Clinical Guidelines',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Clinical Review & Pharmacist Decision Audit Trail
CREATE TABLE IF NOT EXISTS public.clinical_review_audit_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id VARCHAR(100) NOT NULL,
    prescription_id VARCHAR(100) NOT NULL,
    prescription_reference_no VARCHAR(100) NOT NULL,
    patient_id VARCHAR(100) NOT NULL,
    patient_name VARCHAR(255) NOT NULL,
    
    -- Evaluated Context
    prescribed_drugs JSONB NOT NULL,
    active_profile_snapshot JSONB NOT NULL,
    flagged_alerts JSONB NOT NULL, -- Array of clinical alerts generated by the engine
    highest_severity_flagged clinical_alert_severity,
    
    -- Pharmacist Clinical Decision
    decision_action pharmacist_decision_action NOT NULL,
    pharmacist_name VARCHAR(255) NOT NULL,
    pharmacist_role VARCHAR(100) NOT NULL,
    pharmacist_psu_no VARCHAR(100) NOT NULL,
    clinical_override_justification TEXT, -- Mandatory if severe alerts were overridden
    prescriber_contacted_notes TEXT,
    
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Enable Row Level Security (RLS)
ALTER TABLE public.patient_medication_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clinical_interaction_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clinical_review_audit_log ENABLE ROW LEVEL SECURITY;

-- 6. RLS Policies
CREATE POLICY "Allow authenticated read on patient_medication_profiles"
    ON public.patient_medication_profiles FOR SELECT
    USING (auth.role() = 'authenticated' OR true);

CREATE POLICY "Allow authenticated full access on patient_medication_profiles"
    ON public.patient_medication_profiles FOR ALL
    USING (auth.role() = 'authenticated' OR true);

CREATE POLICY "Allow authenticated read on clinical_interaction_rules"
    ON public.clinical_interaction_rules FOR SELECT
    USING (auth.role() = 'authenticated' OR true);

CREATE POLICY "Allow authenticated full access on clinical_review_audit_log"
    ON public.clinical_review_audit_log FOR ALL
    USING (auth.role() = 'authenticated' OR true);

-- 7. Indexes
CREATE INDEX IF NOT EXISTS idx_patient_med_prof_patient ON public.patient_medication_profiles (patient_id);
CREATE INDEX IF NOT EXISTS idx_patient_med_prof_tenant ON public.patient_medication_profiles (tenant_id);
CREATE INDEX IF NOT EXISTS idx_clinical_rules_agent ON public.clinical_interaction_rules (primary_agent_generic);
CREATE INDEX IF NOT EXISTS idx_clinical_audit_rx ON public.clinical_review_audit_log (prescription_id);
